name: Claim fees

on:
  schedule:
    - cron: '0 10 * * 1'

  workflow_dispatch:

jobs:
  claim-protocol-fees:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ secrets.GOR_BOT_REPO_URL }}
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: yarn cache
        uses: actions/cache@v5
        id: yarn-cache
        with:
          path: ~/.cache/yarn
          key: fees-yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            fees-yarn-${{ runner.os }}-

      - name: yarn install
        run: yarn install --frozen-lockfile

      - run: yarn claim:fees:damm
        env:
          RPC_URL: ${{ secrets.DEFAULT_RPC }}
          COOK_OPERATOR_LIVE_JSON: ${{ secrets.COOK_OPERATOR_LIVE_JSON }}

      - run: yarn claim:fees:clmm
        env:
          RPC_URL: ${{ secrets.DEFAULT_RPC }}
          COOK_TREASURY_LIVE_JSON: ${{ secrets.COOK_TREASURY_LIVE_JSON }}
          COOK_OPERATOR_LIVE_JSON: ${{ secrets.COOK_OPERATOR_LIVE_JSON }}

      - run: yarn claim:fees:dbc
        env:
          RPC_URL: ${{ secrets.DEFAULT_RPC }}
          COOK_OPERATOR_LIVE_JSON: ${{ secrets.COOK_OPERATOR_LIVE_JSON }}
