name: Perp

on:
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          repository: ${{ secrets.PERP_BOT_REPO_URL }}
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: perp-cli version
        id: perp-version
        run: echo "version=$(jq -r '.perpCliVersion' config.json)" >> $GITHUB_OUTPUT

      - name: get cli cache
        id: cli-cache
        uses: actions/cache@v4
        with:
          path: bin/.perp-cli-v${{ steps.perp-version.outputs.version }}/node_modules
          key: perp-cli-deps-${{ runner.os }}-${{ steps.perp-version.outputs.version }}
          restore-keys: perp-cli-deps-${{ runner.os }}-

      - name: install cli modules
        if: steps.cli-cache.outputs.cache-hit != 'true'
        run: cd "bin/.perp-cli-v${{ steps.perp-version.outputs.version }}" && npm install
        
      - name: yarn wallet setup
        run: |
          yarn wallet hl ${{ secrets.HL_PRIVATE_KEY }}
          yarn wallet pac ${{ secrets.PACIFICA_PRIVATE_KEY }}

      - run: yarn trade

      - name: trades.json
        run: cat temp/trades.json | jq

      - name: exit
        run: |
          trades=$(cat temp/trades.json | jq -r '.trades')
          if [[ -z "$trades" || "$trades" == "0" ]]; then
            exit 1
          fi
        if: always()

  restart:
    runs-on: ubuntu-latest
    needs: start
    if: success() || failure()
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: restart
        run: gh workflow run perp.yml
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
