name: Poly

on:
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest
    env:
      POLYMARKET_PRIVATE_KEY: ${{ secrets.POLYMARKET_PRIVATE_KEY }}
      POLYMARKET_API_KEY: ${{ secrets.POLYMARKET_API_KEY }}
      POLYMARKET_API_SECRET: ${{ secrets.POLYMARKET_API_SECRET }}
      POLYMARKET_API_PASSPHRASE: ${{ secrets.POLYMARKET_API_PASSPHRASE }}
      POLYMARKET_FUNDER: ${{ secrets.POLYMARKET_FUNDER }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          repository: ${{ secrets.POLY_BOT_REPO_URL }}
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: yarn install
        run: yarn install --frozen-lockfile

      - run: yarn trade

      - run: cat temp/trades.json | jq

      - name: exit
        run: |
          if ! jq -e 'length > 0' temp/trades.json >/dev/null; then
            exit 1
          fi
        if: always()

  restart:
    runs-on: ubuntu-latest
    needs: start
    if: success() || failure()
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: restart
        run: gh workflow run poly.yml
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
